import Link from "next/link"
export default function Home(){
    return(
        <div>
            <Link href="/">
        <h3 className="h3"><i><button>back</button></i></h3>
        </Link>
            <b className="mainHeading">Thermal pollution, </b>sometimes called "thermal enrichment", is the degradation of water quality by any process that changes ambient water temperature. Thermal pollution is the rise or drop in the temperature of a natural body of water caused by human influence. Thermal pollution, unlike chemical pollution, results in a change in the physical properties of water. A common cause of thermal pollution is the use of water as a coolant by power plants and industrial manufacturers.[1] Urban runoff—stormwater discharged to surface waters from rooftops, roads, and parking lots—and reservoirs can also be a source of thermal pollution.[4] Thermal pollution can also be caused by the release of very cold water from the base of reservoirs into warmer rivers.

When water used as a coolant is returned to the natural environment at a higher temperature, the sudden change in temperature decreases oxygen supply and affects ecosystem composition. Fish and other organisms adapted to particular temperature range can be killed by an abrupt change in water temperature (either a rapid increase or decrease) known as "thermal shock". Warm coolant water can also have long term effects on water temperature, increasing the overall temperature of water bodies, including deep water. Seasonality effects how these temperature increases are distributed throughout the water column. Elevated water temperatures decrease oxygen levels, which can kill fish and alter food chain composition, reduce species biodiversity, and foster invasion by new thermophilic species.[5][6]: 375 
<br/>
<b className="mainHeading">Industrial wastewater</b>
In the United States about 75 to 80 percent of thermal pollution is generated by power plants.[6]: 376  The remainder is from industrial sources such as petroleum refineries, pulp and paper mills, chemical plants, steel mills and smelters.[7]: 4–2  [8]

Heated water from these sources may be controlled with:

cooling ponds, man-made bodies of water designed for cooling by evaporation, convection, and radiation
cooling towers, which transfer waste heat to the atmosphere through evaporation and/or heat transfer
cogeneration, a process where waste heat is recycled for domestic and/or industrial heating purposes.[9]
One of the largest contributors to thermal pollution are once-through cooling (OTC) systems which do not reduce temperature as effectively as the above systems. A large power plant may withdraw and export as many as 500 million gallons per day.[10] These systems produce water 10°C warmer on average.[11] For example, the Potrero Generating Station in San Francisco (closed in 2011), used OTC and discharged water to San Francisco Bay approximately 10 °C (20 °F) above the ambient bay temperature.[12] Over 1,200 facilities in the United States use OTC systems as of 2014.[7]: 4–4 

Temperatures can be taken through remote sensing techniques to continually monitor plants' pollution.[13] This aids in quantifying each plants' specific effects, and allows for tighter regulation of thermal pollution.

Converting facilities from once-through cooling to closed-loop systems can significantly decrease the thermal pollution emitted.[10] These systems release water at a temperature more comparable to the natural environment.
<br/>
<b className="mainHeading">Biogeochemical effects</b>
Water warming effects, as opposed to water cooling effects, have been the most studied with regard to biogeochemical effects. Much of this research is on the long term effects of nuclear power plants on lakes after a nuclear power plant has been removed. Overall, there is support for thermal pollution leading to an increase in water temperatures.[25] When power plants are active, short term water temperature increases are correlated with electrical needs, with more coolant released during the winter months. Water warming has also been seen to persist in systems for long periods of time, even after plants have been removed.[3]

When warm water from power plant coolant enters systems, it often mixes leading to general increases in water temperature throughout the water body, including deep cooler water. Specifically in lakes and similar water bodies, stratification leads to different effects on a seasonal basis. In the summer, thermal pollution has been seen to increase deeper water temperature more dramatically than surface water, though stratification still exists, while in the winter surface water temperatures see a larger increase. Stratification is reduced in winter months due to thermal pollution, often eliminating the thermocline.[3]

A study looking at the effect of a removed nuclear power plant in Lake Stechlin, Germany, found a 2.33°C increase persisted in surface water during the winter and a 2.04°C increase persisted in deep water during the summer, with marginal increases throughout the water column in both winter and summer.[3] Stratification and water temperature differences due to thermal pollution seem to correlate with nutrient cycling of phosphorus and nitrogen, as oftentimes water bodies that receive coolant will shift toward eutrophication. No clear data has been obtained on this though, as it is difficult to differentiate influences from other industry and agriculture.[26][27]

Similar to effects seen in aquatic systems due to climatic warming of water, thermal pollution has also been seen to increase surface temperatures in the summer. This can create surface water temperatures that lead to releases of warm air into the atmosphere, increasing air temperature.[3] It therefore can be seen as a contributor to global warming.[28] Many ecological effects will be compounded by climate change as well, as ambient temperature rises in water bodies.[11]

Spacial and climatic factors can impact the severity of water warming due to thermal pollution. High wind speeds tend to increase the impact of thermal pollution. Rivers and large bodies of water also tend to lose the effects of thermal pollution as they progress from the source.[25][29]

Rivers present a unique problem with thermal pollution. As water temperatures are elevated upstream, power plants downstream receive warmer waters. Evidence of this effect has been seen along the Mississippi River, as power plants are forced to use warmer waters as their coolants.[30] This reduces the efficiency of the plants and forces the plants to use more water and produce more thermal pollution.
        </div>
    )
}